using Sdl.Core.Api.DataAccess;
using Sdl.LanguagePlatform.ServerBasedTranslationMemory.Contracts.Entities;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Security;

namespace Sdl.LanguagePlatform.TranslationMemoryApi
{
	/// <summary>
	/// Represents a database server known in the system, which can serve as the host for one or more
	/// translation memory containers (<see cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.TranslationMemoryContainer" />). A translation memory
	/// container is a database that contains one or more server-based
	/// translation memories. 
	/// </summary>
	public class DatabaseServer : IEditableObject, INotifyPropertyChanged, IEquatable<DatabaseServer>, IPermissionCheck
	{
		private DatabaseServerEntity _entity;

		private DatabaseServerEntity _backupEntity;

		internal ReadOnlyCollection<TranslationMemoryContainer> _lazyContainers;

		/// <summary>
		/// Gets or sets the underlying database server entity.
		/// </summary>
		internal DatabaseServerEntity Entity
		{
			get
			{
				return _entity;
			}
			private set
			{
				_entity = value;
				OnPropertyChanged(null);
			}
		}

		/// <summary>
		/// Gets the translation provider server on which this database server is registered.
		/// </summary>
		public TranslationProviderServer TranslationProviderServer
		{
			get;
			private set;
		}

		/// <summary>
		/// Gets the unique Id for this database server.
		/// </summary>
		/// <remarks>This is auto-generated by the system when the database server is created.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to get the unique ID of an entity that no longer exists.</exception>
		public Guid Id
		{
			get
			{
				VerifyNotDeleted();
				return _entity.UniqueId.Value;
			}
		}

		/// <summary>
		/// Gets or sets the friendly name of the database server.
		/// </summary>
		/// <remarks>Note that you have to call <see cref="M:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.Save" /> to persists the change after setting this property.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to get or set name of an entity that no longer exists.</exception>
		[Required(ErrorMessage = "Required Field")]
		[RegularExpression("^[\\w\\s-']*", ErrorMessage = "Characters are not allowed.")]
		[StringLength(50, ErrorMessage = "Name too long!")]
		public string Name
		{
			get
			{
				VerifyNotDeleted();
				return _entity.Name;
			}
			set
			{
				VerifyNotDeleted();
				PropertyValueValidator.Validate(this, value);
				_entity.Name = value;
				OnPropertyChanged("Name");
			}
		}

		/// <summary>
		/// Gets or sets the description of the database server.
		/// </summary>
		/// <remarks>Note that you have to call <see cref="M:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.Save" /> to persists the change after setting this property.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to get/set description of an entity that no longer exists.</exception>
		[StringLength(255, ErrorMessage = "Description too long!")]
		public string Description
		{
			get
			{
				VerifyNotDeleted();
				return _entity.Description;
			}
			set
			{
				VerifyNotDeleted();
				PropertyValueValidator.Validate(this, value);
				_entity.Description = value;
				OnPropertyChanged("Description");
			}
		}

		/// <summary>
		/// Gets or sets the DNS name or IP address of this database server.
		/// </summary>
		/// <remarks>This property can not be changed after the database server has been created.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.NullPropertyException">Thrown when trying to set this property to null or an empty string.</exception>
		/// <exception cref="T:System.InvalidOperationException">Thrown when trying to set this property after initial creation of the database server.</exception>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to get/set ServerName of an entity that no longer exists.</exception>
		[Required]
		[StringLength(255, ErrorMessage = "Server name too long!")]
		public string ServerName
		{
			get
			{
				VerifyNotDeleted();
				return _entity.ServerName;
			}
			set
			{
				VerifyNotDeleted();
				PropertyValueValidator.Validate(this, value);
				if (string.IsNullOrEmpty(value))
				{
					throw new NullPropertyException("Can't set to null or an empty string.");
				}
				if (IsNewObject)
				{
					_entity.ServerName = value;
					OnPropertyChanged("ServerName");
					return;
				}
				throw new InvalidOperationException("ServerName value cannot be re-assigned once it has been initialised.");
			}
		}

		/// <summary>
		/// Gets or sets the database server type.
		/// </summary>
		/// <remarks>This property can not be changed after the database server has been created.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to set ServerType of an entity that no longer exists.</exception>
		/// <exception cref="T:System.InvalidOperationException">Thrown when trying to set this property after initial creation of the database server.</exception>
		[Required(ErrorMessage = "Required Field")]
		public DatabaseServerType ServerType
		{
			get
			{
				VerifyNotDeleted();
				return (DatabaseServerType)_entity.Type.Value;
			}
			set
			{
				VerifyNotDeleted();
				if (!IsNewObject)
				{
					throw new InvalidOperationException("ServerType cannot be re-assigned once it has been initialised");
				}
				_entity.Type = (Sdl.LanguagePlatform.ServerBasedTranslationMemory.Contracts.Entities.DatabaseServerType)value;
				OnPropertyChanged("ServerType");
			}
		}

		/// <summary>
		/// Gets or sets the type of authentication that is used when the application server communicates with this database server.
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to set AuthenticationType of an entity that no longer exists.</exception>
		public DatabaseServerAuthenticationType AuthenticationType
		{
			get
			{
				VerifyNotDeleted();
				return (DatabaseServerAuthenticationType)_entity.AuthenticationType.Value;
			}
			set
			{
				if (_entity == null)
				{
					throw new ObjectDeletedException("Database Server must have been deleted, contents are null.");
				}
				_entity.AuthenticationType = (Sdl.LanguagePlatform.ServerBasedTranslationMemory.Contracts.Entities.DatabaseServerAuthenticationType)value;
				OnPropertyChanged("AuthenticationType");
			}
		}

		/// <summary>
		/// Gets or sets the user name used for authentication together with the password specified in <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.Password" /> when the application server communicates with this database server.
		/// </summary>
		/// <remarks>The user name is only used when <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.AuthenticationType" /> is set to <see cref="F:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServerAuthenticationType.Database" />.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to set UserName of an entity that no longer exists.</exception>
		[Required(ErrorMessage = "Required Field")]
		[StringLength(50, ErrorMessage = "User Name too long!")]
		public string UserName
		{
			get
			{
				VerifyNotDeleted();
				return _entity.UserName;
			}
			set
			{
				VerifyNotDeleted();
				if (_entity.UserName != null && value != null && AuthenticationType == DatabaseServerAuthenticationType.Database)
				{
					PropertyValueValidator.Validate(this, value);
				}
				_entity.UserName = value;
				OnPropertyChanged("UserName");
			}
		}

		/// <summary>
		/// Gets or sets the password for the user name specified in <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.UserName" /> that is used for authentication when the application server communicates with this database server.
		/// </summary>
		/// <remarks>The password is only used when <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.AuthenticationType" /> is set to <see cref="F:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServerAuthenticationType.Database" />.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to set Password of an entity that no longer exists.</exception>
		[Required(ErrorMessage = "Required Field")]
		[StringLength(50, ErrorMessage = "Password too long!")]
		public string Password
		{
			get
			{
				VerifyNotDeleted();
				return _entity.Password;
			}
			set
			{
				VerifyNotDeleted();
				if (_entity.Password != null && value != null && AuthenticationType == DatabaseServerAuthenticationType.Database)
				{
					PropertyValueValidator.Validate(this, value);
				}
				_entity.Password = value;
				OnPropertyChanged("Password");
			}
		}

		/// <summary>
		/// Gets all the translation memory containers that are hosted on this database server.
		/// </summary>
		/// <remarks>If the list of containers has been pre-loaded, the in-memory collection of containers is returned, otherwise
		/// the list of containers is retrieved from the server on-demand.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has already been deleted.</exception>
		public ReadOnlyCollection<TranslationMemoryContainer> Containers
		{
			get
			{
				VerifyNotDeleted();
				if (_lazyContainers == null)
				{
					ContainerEntity[] containersByDatabaseServerId = TranslationProviderServer.Service.GetContainersByDatabaseServerId(_entity.Id, new string[0]);
					List<TranslationMemoryContainer> list = new List<TranslationMemoryContainer>();
					ClientObjectBuilder clientObjectBuilder = new ClientObjectBuilder(TranslationProviderServer);
					clientObjectBuilder[clientObjectBuilder.CreateKey(Entity)] = this;
					ContainerEntity[] array = containersByDatabaseServerId;
					foreach (ContainerEntity entity in array)
					{
						list.Add(TranslationMemoryContainer.BuildTranslationMemoryContainer(clientObjectBuilder, entity));
					}
					_lazyContainers = list.AsReadOnly();
				}
				return _lazyContainers;
			}
		}

		/// <summary>
		/// Gets the parent resource group path.
		/// </summary>
		public string ParentResourceGroupPath
		{
			get
			{
				return _entity.ParentResourceGroupPath;
			}
			set
			{
				_entity.ParentResourceGroupPath = value;
			}
		}

		/// <summary>
		/// Gets or sets the parent resource group name.
		/// </summary>
		public string ParentResourceGroupName
		{
			get
			{
				return _entity.ParentResourceGroupName;
			}
			set
			{
				_entity.ParentResourceGroupName = value;
			}
		}

		/// <summary>
		/// Gets the parent resource group description.
		/// </summary>
		public string ParentResourceGroupDescription
		{
			get
			{
				return _entity.ParentResourceGroupDescription;
			}
			set
			{
				_entity.ParentResourceGroupDescription = value;
			}
		}

		/// <summary>
		/// Gets or sets the collection of paths for the linked resource groups.
		/// </summary>
		public string[] LinkedResourceGroupPaths
		{
			get
			{
				return _entity.LinkedResourceGroupPaths;
			}
			set
			{
				_entity.LinkedResourceGroupPaths = value;
			}
		}

		/// <summary>
		/// Returns <code>true</code> if this database server has unsaved changes.
		/// </summary>
		public bool IsDirty
		{
			get
			{
				if (_entity == null)
				{
					return false;
				}
				return _entity.IsDirty;
			}
		}

		/// <summary>
		/// Returns <code>true</code> if this translation memory has been deleted.
		/// </summary>
		public bool IsDeleted => _entity == null;

		/// <summary>
		/// Gets a value indicating whether this instance is new object.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if this instance is new object; otherwise, <c>false</c>.
		/// </value>
		public bool IsNewObject
		{
			get
			{
				if (_entity == null)
				{
					return false;
				}
				if (_entity.Id != null)
				{
					return _entity.Id.Value == null;
				}
				return true;
			}
		}

		/// <summary>
		/// Occurs when a property value changes.
		/// </summary>
		public event PropertyChangedEventHandler PropertyChanged;

		internal static DatabaseServer BuildDatabaseServer(ClientObjectBuilder builder, DatabaseServerEntity entity)
		{
			ClientObjectKey key = builder.CreateKey(entity);
			DatabaseServer databaseServer = builder[key] as DatabaseServer;
			if (databaseServer != null)
			{
				return databaseServer;
			}
			databaseServer = (DatabaseServer)(builder[key] = new DatabaseServer(builder.Server, entity));
			if (entity.Containers.IsLoaded)
			{
				List<TranslationMemoryContainer> list = new List<TranslationMemoryContainer>();
				foreach (ContainerEntity container in entity.Containers)
				{
					TranslationMemoryContainer item = TranslationMemoryContainer.BuildTranslationMemoryContainer(builder, container);
					list.Add(item);
				}
				databaseServer._lazyContainers = list.AsReadOnly();
				entity.Containers = new EntityCollection<ContainerEntity>();
			}
			return databaseServer;
		}

		/// <summary>
		/// Creates a new database server. Note that you have to call <see cref="M:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.Save" /> to 
		/// persist the database server object, after setting all the required properties.
		/// </summary>
		/// <param name="server">The translation provider server with which the database server should be registered.</param>
		/// <exception cref="T:System.ArgumentNullException">Thrown when <paramref name="server" /> is null.</exception>
		public DatabaseServer(TranslationProviderServer server)
		{
			if (server == null)
			{
				throw new ArgumentNullException("server");
			}
			TranslationProviderServer = server;
			_entity = new DatabaseServerEntity
			{
				Type = Sdl.LanguagePlatform.ServerBasedTranslationMemory.Contracts.Entities.DatabaseServerType.SqlServer,
				AuthenticationType = Sdl.LanguagePlatform.ServerBasedTranslationMemory.Contracts.Entities.DatabaseServerAuthenticationType.Windows,
				UniqueId = Guid.NewGuid()
			};
			_lazyContainers = new ReadOnlyCollection<TranslationMemoryContainer>(new List<TranslationMemoryContainer>());
		}

		/// <summary>
		/// Constructor for existing database servers.
		/// </summary>
		/// <param name="server">The server to which the database server belongs.</param>
		/// <param name="entity">The database server entity.</param>
		/// <exception cref="T:System.ArgumentNullException">Thrown when trying to set TranslationProviderServer to null.</exception>
		/// <exception cref="T:System.ArgumentNullException">Thrown when trying to set DatabaseServerEntity to null.</exception>
		/// <exception cref="T:System.ArgumentException">Thrown when DatabaseServer id is not set.</exception>
		internal DatabaseServer(TranslationProviderServer server, DatabaseServerEntity entity)
		{
			if (server == null)
			{
				throw new ArgumentNullException("server");
			}
			if (entity == null)
			{
				throw new ArgumentNullException("entity");
			}
			if (entity.Id == null || entity.Id.Value == null)
			{
				throw new ArgumentException(StringResources.DatabaseServer_EntityHasNoId, "entity");
			}
			TranslationProviderServer = server;
			_entity = entity;
		}

		/// <summary>
		/// Deletes this database server and all its containers from the system. 
		/// <param name="deleteContainerDatabases">Whether to delete the physical container databases.</param>
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has already been deleted.</exception>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectNotSavedException">Thrown when this object has not been initially saved yet.</exception>
		public void Delete(bool deleteContainerDatabases)
		{
			VerifyNotDeleted();
			VerifyExistingObject("Database Server has to be saved before it can be deleted.");
			VerifyPermission("tmdbserver.delete");
			TranslationProviderServer.Service.DeleteDatabaseServer(_entity.Id, deleteContainerDatabases);
			_entity = null;
		}

		/// <summary>
		/// Adds a container to the lazy load container list. This is ONLY to be used by a container to update it's associated DatabaseServer.
		/// </summary>
		internal void AddContainer(TranslationMemoryContainer container)
		{
			List<TranslationMemoryContainer> list = new List<TranslationMemoryContainer>(Containers)
			{
				container
			};
			_lazyContainers = list.AsReadOnly();
		}

		/// <summary>
		/// Removes a container from the lazy load container list. This is ONLY to be used by a container to update it's associatated DatabaseServer.
		/// </summary>
		internal bool DeleteContainer(TranslationMemoryContainer container)
		{
			List<TranslationMemoryContainer> list = new List<TranslationMemoryContainer>(Containers);
			bool result = list.Remove(container);
			_lazyContainers = list.AsReadOnly();
			return result;
		}

		/// <summary>
		/// Saves this database server.
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has already been deleted.</exception>
		public void Save()
		{
			VerifyNotDeleted();
			if (IsNewObject)
			{
				_entity = TranslationProviderServer.Service.CreateDatabaseServer(_entity, ParentResourceGroupPath);
				return;
			}
			VerifyPermission("tmdbserver.edit");
			_entity = TranslationProviderServer.Service.UpdateDatabaseServer(_entity);
		}

		/// <summary>
		/// Gets whether this object has the permission with the specified name.
		/// </summary>
		/// <param name="permission">The permission name.</param>
		/// <returns>
		/// 	<code>true</code> is the object has the specified permission.
		/// </returns>
		public bool HasPermission(string permission)
		{
			VerifyNotDeleted();
			if (_entity.Permissions != null)
			{
				return _entity.Permissions.HasPermission(permission);
			}
			return true;
		}

		private void VerifyExistingObject(string message)
		{
			if (IsNewObject)
			{
				throw new ObjectDeletedException(message);
			}
		}

		private void VerifyNotDeleted(string message)
		{
			if (IsDeleted)
			{
				throw new ObjectDeletedException(message);
			}
		}

		private void VerifyNotDeleted()
		{
			VerifyNotDeleted("The database server has been deleted.");
		}

		private void VerifyPermission(string permission)
		{
			if (!HasPermission(permission))
			{
				throw new SecurityException($"Current user does not have {permission} permission on this database server.");
			}
		}

		private void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit()
		{
			if (_entity != null && _backupEntity == null)
			{
				_backupEntity = new DatabaseServerEntity();
				_backupEntity.Id = _entity.Id;
				_backupEntity.Name = _entity.Name;
				_backupEntity.Description = _entity.Description;
				_backupEntity.Password = _entity.Password;
				_backupEntity.ServerName = _entity.ServerName;
				_backupEntity.Type = _entity.Type;
				_backupEntity.UniqueId = _entity.UniqueId;
				_backupEntity.UserName = _entity.UserName;
				_backupEntity.AuthenticationType = _entity.AuthenticationType;
				_backupEntity.MarkAsClean();
			}
		}

		/// <summary>
		/// Discards changes since the last <see cref="M:System.ComponentModel.IEditableObject.BeginEdit" /> call.
		/// </summary>
		void IEditableObject.CancelEdit()
		{
			if (_entity != null && _backupEntity != null)
			{
				Entity = _backupEntity;
				_backupEntity = null;
			}
		}

		/// <summary>
		/// Pushes changes since the last <see cref="M:System.ComponentModel.IEditableObject.BeginEdit" /> or <see cref="M:System.ComponentModel.IBindingList.AddNew" /> call into the underlying object.
		/// </summary>
		void IEditableObject.EndEdit()
		{
			_backupEntity = null;
		}

		/// <summary>
		/// Indicates whether the current object is equal to another object of the same type.
		/// </summary>
		/// <param name="other">An object to compare with this object.</param>
		/// <returns>
		/// true if the current object is equal to the <paramref name="other" /> parameter; otherwise, false.
		/// </returns>
		public bool Equals(DatabaseServer other)
		{
			return Id == other.Id;
		}

		/// <summary>
		/// Determines whether the specified <see cref="T:System.Object" /> is equal to this instance.
		/// </summary>
		/// <param name="obj">The <see cref="T:System.Object" /> to compare with this instance.</param>
		/// <returns>
		/// 	<c>true</c> if the specified <see cref="T:System.Object" /> is equal to this instance; otherwise, <c>false</c>.
		/// </returns>
		/// <exception cref="T:System.NullReferenceException">
		/// The <paramref name="obj" /> parameter is null.
		/// </exception>
		public override bool Equals(object obj)
		{
			DatabaseServer databaseServer = (DatabaseServer)obj;
			if (databaseServer != null)
			{
				return Equals(databaseServer);
			}
			return false;
		}

		/// <summary>
		/// Returns a hash code for this instance.
		/// </summary>
		/// <returns>
		/// A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. 
		/// </returns>
		public override int GetHashCode()
		{
			return Id.GetHashCode();
		}
	}
}
