using Sdl.LanguagePlatform.Core.Tokenization;
using Sdl.LanguagePlatform.ServerBasedTranslationMemory.Contracts.Entities;
using Sdl.LanguagePlatform.TranslationMemory;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;

namespace Sdl.LanguagePlatform.TranslationMemoryApi
{
	/// <summary>
	/// Base class used by ServerBasedTranslationMemory and CloudBasedTranslationMemory
	/// </summary>
	public abstract class RemoteTranslationMemory : INotifyPropertyChanged, IEditableObject
	{
		internal TranslationMemoryEntity Entity
		{
			get;
			set;
		}

		/// <summary>
		///
		/// </summary>
		protected TranslationMemoryEntity BackupEntity
		{
			get;
			private set;
		}

		/// <summary>
		/// Gets the user-friendly name of this provider. It is not necessarily unique across the system.
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has been deleted.</exception>
		[Required(ErrorMessage = "Required Field")]
		[StringLength(150, ErrorMessage = "Name too long!")]
		public string Name
		{
			get
			{
				VerifyNotDeleted();
				return Entity.Name;
			}
			set
			{
				VerifyNotDeleted();
				char[] invalidPathChars = Path.GetInvalidPathChars();
				if (invalidPathChars.Any((char invalidChar) => value.Contains(invalidChar)))
				{
					throw new InvalidOperationException("Name contains invalid characters");
				}
				PropertyValueValidator.Validate(this, value);
				Entity.Name = value;
				OnPropertyChanged("Name");
			}
		}

		/// <summary>
		/// Gets or sets the description of the tm.
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has been deleted.</exception>
		[StringLength(255, ErrorMessage = "Description too long!")]
		public string Description
		{
			get
			{
				VerifyNotDeleted();
				return Entity.Description;
			}
			set
			{
				VerifyNotDeleted();
				PropertyValueValidator.Validate(this, value);
				Entity.Description = value;
				OnPropertyChanged("Description");
			}
		}

		/// <summary>
		/// Gets or sets a unique Id for this database server.
		/// </summary>
		/// <remarks>This is auto-generated by the system.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has been deleted.</exception>
		public Guid Id
		{
			get
			{
				VerifyNotDeleted();
				return Entity.UniqueId.Value;
			}
		}

		/// <summary>
		/// Gets or sets the copyright of the translation memory.
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has been deleted.</exception>
		[StringLength(1024, ErrorMessage = "Copyright too long!")]
		public string Copyright
		{
			get
			{
				VerifyNotDeleted();
				return Entity.Copyright;
			}
			set
			{
				VerifyNotDeleted();
				PropertyValueValidator.Validate(this, value);
				Entity.Copyright = value;
				OnPropertyChanged("Copyright");
			}
		}

		/// <summary>
		/// Gets the creation date of this translation memory.
		/// </summary>
		/// <value></value>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has been deleted.</exception>
		public DateTime CreationDate
		{
			get
			{
				VerifyNotDeleted();
				if (Entity.CreationDate.HasValue)
				{
					return Entity.CreationDate.Value;
				}
				return default(DateTime);
			}
		}

		/// <summary>
		/// Gets or sets the recognizers which are enabled for this TM.
		/// <remarks>Note that changing recognizers may require reindexing. In addition, in
		/// some cases duplicate TUs may be in the TM if recognizers are enabled which have
		/// been disabled before.</remarks>
		/// </summary>
		/// <value></value>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has been deleted.</exception>
		public BuiltinRecognizers Recognizers
		{
			get
			{
				VerifyNotDeleted();
				return Entity.Recognizers.Value;
			}
			set
			{
				VerifyNotDeleted();
				Entity.Recognizers = value;
				OnPropertyChanged("Recognizers");
			}
		}

		/// <summary>
		/// Gets or sets the set of fuzzy indices defined on this TM.
		/// </summary>
		/// <value></value>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has been deleted.</exception>
		public FuzzyIndexes FuzzyIndexes
		{
			get
			{
				VerifyNotDeleted();
				return Entity.FuzzyIndexes.Value;
			}
			set
			{
				VerifyNotDeleted();
				Entity.FuzzyIndexes = value;
				OnPropertyChanged("FuzzyIndexes");
			}
		}

		/// <summary>
		/// Returns <code>true</code> if this translation memory has not been saved yet.
		/// </summary>
		public bool IsNewObject
		{
			get
			{
				if (Entity.Id != null)
				{
					return Entity.Id.Value == null;
				}
				return true;
			}
		}

		/// <summary>
		/// Returns <code>true</code> if this translation memory has been deleted.
		/// </summary>
		public bool IsDeleted => Entity == null;

		private event PropertyChangedEventHandler PropertyChangedPrivate;

		/// <summary>
		/// Occurs when a property value changes.
		/// </summary>
		event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged
		{
			add
			{
				PropertyChangedPrivate += value;
			}
			remove
			{
				PropertyChangedPrivate -= value;
			}
		}

		/// <summary>
		///
		/// </summary>
		/// <param name="entity"></param>
		protected RemoteTranslationMemory(TranslationMemoryEntity entity)
		{
			Entity = entity;
		}

		/// <summary>
		///
		/// </summary>
		/// <param name="property"></param>
		protected void OnPropertyChanged(string property)
		{
			this.PropertyChangedPrivate?.Invoke(this, new PropertyChangedEventArgs(property));
		}

		/// <summary>
		/// Verifies that translation memory has not been deleted.
		/// </summary>
		protected void VerifyNotDeleted()
		{
			VerifyNotDeleted("The translation memory has been deleted.");
		}

		private void VerifyNotDeleted(string message)
		{
			if (IsDeleted)
			{
				throw new ObjectDeletedException(message);
			}
		}

		void IEditableObject.BeginEdit()
		{
			if (Entity != null && BackupEntity == null)
			{
				BackupEntity = Entity.Clone();
				BackupEntity.MarkAsClean();
			}
		}

		void IEditableObject.CancelEdit()
		{
			if (Entity != null && BackupEntity != null)
			{
				Entity = BackupEntity;
				BackupEntity = null;
			}
		}

		void IEditableObject.EndEdit()
		{
			BackupEntity = null;
		}
	}
}
