using Sdl.Core.Api.DataAccess;
using Sdl.LanguagePlatform.ServerBasedTranslationMemory.Contracts.Entities;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security;

namespace Sdl.LanguagePlatform.TranslationMemoryApi
{
	/// <summary>
	/// Represents a database using for storing server-based translation memories. 
	/// </summary>
	public class TranslationMemoryContainer : IEditableObject, INotifyPropertyChanged, IEquatable<TranslationMemoryContainer>, IPermissionCheck
	{
		private ContainerEntity _entity;

		private ContainerEntity _backupEntity;

		internal DatabaseServer _lazyDatabaseServer;

		internal ReadOnlyCollection<ServerBasedTranslationMemory> _lazyTranslationMemories;

		internal IList<string> _lazyTranslationMemoryNames;

		private string _userName;

		private string _password;

		internal ContainerEntity Entity
		{
			get
			{
				return _entity;
			}
			private set
			{
				_entity = value;
				OnPropertyChanged(null);
			}
		}

		/// <summary>
		/// Gets the server.
		/// </summary>
		public TranslationProviderServer TranslationProviderServer
		{
			get;
			private set;
		}

		/// <summary>
		/// Gets the unique ID for this database server.
		/// </summary>
		/// <remarks>This is auto-generated by the system when the container is created.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to get the ID of an entity that no longer exists.</exception>
		public Guid Id
		{
			get
			{
				VerifyNotDeleted();
				return _entity.UniqueId.Value;
			}
		}

		/// <summary>
		/// Gets or sets the friendly name of the container.
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to get/set name of an entity that no longer exists.</exception>
		[Required(ErrorMessage = "Required Field")]
		[RegularExpression("[^\\\\/\"<>\\|\\*\\?%]+", ErrorMessage = "The following characters ^ \\ / \\\"  < > | * ? %  are not allowed")]
		[StringLength(50, ErrorMessage = "Name cannot exceed 50 characters.")]
		public string Name
		{
			get
			{
				VerifyNotDeleted();
				return _entity.Name;
			}
			set
			{
				VerifyNotDeleted();
				PropertyValueValidator.Validate(this, value);
				_entity.Name = value;
				OnPropertyChanged("Name");
			}
		}

		/// <summary>
		/// Gets or sets the description of the container.
		/// </summary>
		/// <value>The description.</value>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to get/set description of an entity that no longer exists.</exception>
		[StringLength(255, ErrorMessage = "Description too long!")]
		public string Description
		{
			get
			{
				VerifyNotDeleted();
				return _entity.Description;
			}
			set
			{
				VerifyNotDeleted();
				PropertyValueValidator.Validate(this, value);
				_entity.Description = value;
				OnPropertyChanged("Description");
			}
		}

		/// <summary>
		/// Gets or sets the database name.
		/// </summary>
		/// <remarks>If the database does not exist yet, it will be created automatically. If the database already exists, it will be registered
		/// with the system, together with any translation memories it contains.</remarks>
		/// <remarks>This property can not be changed after the database server has been created.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.NullPropertyException">Thrown when trying to set this property to null or an empty string.</exception>
		/// <exception cref="T:System.InvalidOperationException">Thrown when trying to set this property after initial creation of the database server.</exception>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to get/set DatabaseName of an entity that no longer exists.</exception>
		[Required(ErrorMessage = "Required Field")]
		[RegularExpression("^[\\p{L}_][\\w_@#\\$]*$", ErrorMessage = "Only alpha-numeric and underscore characters allowed.")]
		[StringLength(123, ErrorMessage = "Database Name cannot exceed 123 characters.")]
		public string DatabaseName
		{
			get
			{
				VerifyNotDeleted();
				return _entity.DatabaseName;
			}
			set
			{
				VerifyNotDeleted();
				if (DatabaseServer == null || DatabaseServer.ServerType == DatabaseServerType.SqlServer)
				{
					PropertyValueValidator.Validate(this, value);
				}
				_entity.DatabaseName = value;
				OnPropertyChanged("DatabaseName");
			}
		}

		/// <summary>
		/// Gets or sets the user name used for TM container together with the password specified in <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.TranslationMemoryContainer.Password" />.
		/// </summary>
		/// <remarks>The user name is only used when <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.ServerType" /> is set to <see cref="F:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServerType.Oracle" />.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to set UserName of an entity that no longer exists.</exception>
		[Required(ErrorMessage = "Required Field")]
		[StringLength(30, ErrorMessage = "User Name too long!")]
		public string UserName
		{
			get
			{
				VerifyNotDeleted();
				if (!string.IsNullOrEmpty(_entity.DatabaseName))
				{
					string[] array = _entity.DatabaseName.Split('#');
					_userName = ((array.Length == 1) ? _entity.DatabaseName : array[0]);
				}
				return _userName;
			}
			set
			{
				VerifyNotDeleted();
				if (_userName != null && value != null && DatabaseServer.ServerType == DatabaseServerType.Oracle)
				{
					PropertyValueValidator.Validate(this, value);
				}
				_userName = value;
				if (!string.IsNullOrEmpty(_userName) && !string.IsNullOrEmpty(_password))
				{
					_entity.DatabaseName = $"{_userName}#{_password}";
					OnPropertyChanged("DatabaseName");
				}
				OnPropertyChanged("UserName");
			}
		}

		/// <summary>
		/// Gets or sets the password for the user name specified in <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.TranslationMemoryContainer.UserName" /> that is used for TM container.
		/// </summary>
		/// <remarks>The password is only used when <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.ServerType" /> is set to <see cref="F:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServerType.Oracle" />.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when trying to set Password of an entity that no longer exists.</exception>
		[Required(ErrorMessage = "Required Field")]
		[StringLength(30, ErrorMessage = "Password too long!")]
		public string Password
		{
			get
			{
				VerifyNotDeleted();
				if (!string.IsNullOrEmpty(_entity.DatabaseName))
				{
					string[] array = _entity.DatabaseName.Split('#');
					if (array.Length != 1)
					{
						return array[1];
					}
					return _entity.DatabaseName;
				}
				return _password;
			}
			set
			{
				VerifyNotDeleted();
				if (_password != null && value != null && DatabaseServer.ServerType == DatabaseServerType.Oracle)
				{
					PropertyValueValidator.Validate(this, value);
				}
				_password = value;
				if (DatabaseServer.ServerType == DatabaseServerType.Oracle)
				{
					_entity.DatabaseName = $"{UserName}#{_password}";
					OnPropertyChanged("DatabaseName");
				}
				OnPropertyChanged("Password");
			}
		}

		/// <summary>
		/// Returns the human readable string of the TM container.
		/// </summary>
		public string DisplayText => $"{Name} ({((DatabaseServer.ServerType == DatabaseServerType.Oracle) ? UserName : DatabaseName)})";

		/// <summary>
		/// Gets or sets the database server this container belongs to.
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.NullPropertyException">Thrown when trying to set this property to null or is already null.</exception>
		/// <exception cref="T:System.InvalidOperationException">Thrown when trying to set this property after initial creation of the database server.</exception>
		[Required(ErrorMessage = "You must select a database server")]
		public DatabaseServer DatabaseServer
		{
			get
			{
				if (_lazyDatabaseServer == null && _entity.DatabaseServer.ForeignKey != null)
				{
					DatabaseServerEntity databaseServerById = TranslationProviderServer.Service.GetDatabaseServerById(_entity.DatabaseServer.ForeignKey, new string[0]);
					_lazyDatabaseServer = new DatabaseServer(TranslationProviderServer, databaseServerById);
				}
				return _lazyDatabaseServer;
			}
			set
			{
				PropertyValueValidator.Validate(this, value);
				_lazyDatabaseServer = value;
				_entity.DatabaseServer.ForeignKey = _lazyDatabaseServer.Entity.Id;
				OnPropertyChanged("DatabaseServer");
			}
		}

		/// <summary>
		/// Gets the translation memories in this container.
		/// </summary>
		public ReadOnlyCollection<ServerBasedTranslationMemory> TranslationMemories
		{
			get
			{
				if (_lazyTranslationMemories == null)
				{
					TranslationMemoryEntity[] translationMemoryByContainerId = TranslationProviderServer.Service.GetTranslationMemoryByContainerId(Entity.Id, TranslationProviderServer.GetDefaultTranslationMemoryRelationships(), includeLanguageResourceData: false, includeScheduledOperations: false);
					ClientObjectBuilder clientObjectBuilder = new ClientObjectBuilder(TranslationProviderServer);
					clientObjectBuilder[clientObjectBuilder.CreateKey(Entity)] = this;
					List<ServerBasedTranslationMemory> list = new List<ServerBasedTranslationMemory>();
					TranslationMemoryEntity[] array = translationMemoryByContainerId;
					foreach (TranslationMemoryEntity entity in array)
					{
						list.Add(ServerBasedTranslationMemory.BuildServerBasedTranslationMemory(clientObjectBuilder, entity));
					}
					_lazyTranslationMemories = list.AsReadOnly();
				}
				return _lazyTranslationMemories;
			}
		}

		/// <summary>
		/// Returns the list of translation memory names in this container.
		/// </summary>
		public IList<string> TranslationMemoryNames
		{
			get
			{
				if (_lazyTranslationMemoryNames == null)
				{
					LoadTranslationMemoryNames();
				}
				return _lazyTranslationMemoryNames;
			}
		}

		/// <summary>
		/// Gets or sets the parent resource group path.
		/// </summary>
		/// <value>The parent resource group path.</value>
		[Required(ErrorMessage = "Required Field")]
		public string ParentResourceGroupPath
		{
			get
			{
				return _entity.ParentResourceGroupPath;
			}
			set
			{
				_entity.ParentResourceGroupPath = value;
			}
		}

		/// <summary>
		/// Gets the parent resource group name.
		/// </summary>
		public string ParentResourceGroupName
		{
			get
			{
				return _entity.ParentResourceGroupName;
			}
			set
			{
				_entity.ParentResourceGroupName = value;
			}
		}

		/// <summary>
		/// Gets the parent resource group description.
		/// </summary>
		public string ParentResourceGroupDescription
		{
			get
			{
				return _entity.ParentResourceGroupDescription;
			}
			set
			{
				_entity.ParentResourceGroupDescription = value;
			}
		}

		/// <summary>
		/// Gets the collection of paths for the linked resource groups.
		/// </summary>
		public string[] LinkedResourceGroupPaths
		{
			get
			{
				return _entity.LinkedResourceGroupPaths;
			}
			set
			{
				_entity.LinkedResourceGroupPaths = value;
			}
		}

		/// <summary>
		/// Returns <code>true</code> if this container has unsaved changes.
		/// </summary>
		public bool IsDirty
		{
			get
			{
				if (_entity == null)
				{
					return false;
				}
				return _entity.IsDirty;
			}
		}

		/// <summary>
		/// Returns <code>true</code> if this translation memory has been deleted.
		/// </summary>
		public bool IsDeleted => _entity == null;

		/// <summary>
		/// Gets a value indicating whether this instance is new object.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if this instance is new object; otherwise, <c>false</c>.
		/// </value>
		public bool IsNewObject
		{
			get
			{
				if (_entity == null)
				{
					return false;
				}
				if (_entity.Id != null)
				{
					return _entity.Id.Value == null;
				}
				return true;
			}
		}

		/// <summary>
		/// Occurs when a property value changes.
		/// </summary>
		public event PropertyChangedEventHandler PropertyChanged;

		internal static TranslationMemoryContainer BuildTranslationMemoryContainer(ClientObjectBuilder builder, ContainerEntity entity)
		{
			ClientObjectKey key = builder.CreateKey(entity);
			TranslationMemoryContainer translationMemoryContainer = builder[key] as TranslationMemoryContainer;
			if (translationMemoryContainer != null)
			{
				return translationMemoryContainer;
			}
			translationMemoryContainer = (TranslationMemoryContainer)(builder[key] = new TranslationMemoryContainer(builder.Server, entity));
			ClientObjectKey key2 = builder.CreateKey<DatabaseServerEntity>(entity.DatabaseServer.ForeignKey);
			DatabaseServer databaseServer = builder[key2] as DatabaseServer;
			if (databaseServer == null && entity.DatabaseServer.Entity != null)
			{
				databaseServer = DatabaseServer.BuildDatabaseServer(builder, entity.DatabaseServer.Entity);
			}
			entity.DatabaseServer = new EntityReference<DatabaseServerEntity>(entity.DatabaseServer.ForeignKey);
			translationMemoryContainer._lazyDatabaseServer = databaseServer;
			if (entity.TranslationMemories.IsLoaded)
			{
				List<ServerBasedTranslationMemory> list = new List<ServerBasedTranslationMemory>();
				foreach (TranslationMemoryEntity translationMemory in entity.TranslationMemories)
				{
					ServerBasedTranslationMemory item = ServerBasedTranslationMemory.BuildServerBasedTranslationMemory(builder, translationMemory);
					list.Add(item);
				}
				translationMemoryContainer._lazyTranslationMemories = list.AsReadOnly();
				entity.TranslationMemories = new EntityCollection<TranslationMemoryEntity>();
			}
			return translationMemoryContainer;
		}

		/// <summary>
		/// Creates a new translation memory container. Note that you have to call <see cref="M:Sdl.LanguagePlatform.TranslationMemoryApi.TranslationMemoryContainer.Save" /> to 
		/// persist the container object, after setting all the required properties.
		/// </summary>
		/// <param name="server">The translation provider server with which the container should be registered.</param>
		/// <exception cref="T:System.ArgumentNullException">Thrown when <paramref name="server" /> is null.</exception>
		public TranslationMemoryContainer(TranslationProviderServer server)
		{
			if (server == null)
			{
				throw new ArgumentNullException("server");
			}
			TranslationProviderServer = server;
			_entity = new ContainerEntity
			{
				UniqueId = Guid.NewGuid()
			};
		}

		/// <summary>
		/// Creates a translation memory container object for an existing container.
		/// </summary>
		/// <param name="server">The translation provider server.</param>
		/// <param name="entity">The entity representing the translation memory container.</param>
		/// <exception cref="T:System.ArgumentNullException">Thrown when trying to set TranslationProviderServer to null.</exception>
		/// <exception cref="T:System.ArgumentNullException">Thrown when trying to set ContainerEntity to null.</exception>
		/// <exception cref="T:System.ArgumentException">Thrown when TranslationMemory id is not set.</exception>
		internal TranslationMemoryContainer(TranslationProviderServer server, ContainerEntity entity)
		{
			if (server == null)
			{
				throw new ArgumentNullException("server");
			}
			if (entity == null)
			{
				throw new ArgumentNullException("entity");
			}
			if (entity.Id == null || entity.Id.Value == null)
			{
				throw new ArgumentException(StringResources.TranslationMemoryContainer_EntryHasNoID, "entity");
			}
			TranslationProviderServer = server;
			_entity = entity;
		}

		/// <summary>
		/// Creates a translation memory container object for an existing container.
		/// </summary>
		/// <param name="databaseServer">The database server.</param>
		/// <param name="entity">The entity.</param>
		/// <exception cref="T:System.ArgumentNullException">Thrown when trying to set TranslationProviderServer to null.</exception>
		/// <exception cref="T:System.ArgumentNullException">Thrown when trying to set DatabaseServer to null.</exception>
		/// <exception cref="T:System.ArgumentNullException">Thrown when trying to set ContainerEntity to null.</exception>
		/// <exception cref="T:System.ArgumentException">Thrown when TranslationMemory id is not set.</exception>
		internal TranslationMemoryContainer(DatabaseServer databaseServer, ContainerEntity entity)
		{
			if (databaseServer == null)
			{
				throw new ArgumentNullException("databaseServer");
			}
			if (databaseServer.TranslationProviderServer == null)
			{
				throw new ArgumentNullException("databaseServer.TranslationProviderServer");
			}
			if (entity == null)
			{
				throw new ArgumentNullException("entity");
			}
			if (entity.Id == null || entity.Id.Value == null)
			{
				throw new ArgumentException(StringResources.TranslationMemoryContainer_EntryHasNoID, "entity");
			}
			TranslationProviderServer = databaseServer.TranslationProviderServer;
			_entity = entity;
			_lazyDatabaseServer = databaseServer;
		}

		/// <summary>
		/// Initializes the lazy TranslationMemoryNames property.
		/// </summary>
		public void LoadTranslationMemoryNames()
		{
			_lazyTranslationMemoryNames = TranslationProviderServer.Service.GetTranslationMemoryNamesByContainerId(Entity.Id).ToList();
		}

		/// <summary>
		/// Deletes this translation memory container.
		/// </summary>
		/// <param name="deleteContainerDatabase">Whether to delete the physical container database. When <code>false</code>, this just unregisters the
		/// container from the system.</param>
		/// <remarks>Note that this automatically updates the <see cref="P:Sdl.LanguagePlatform.TranslationMemoryApi.DatabaseServer.Containers" /> collection if that has been loaded already.</remarks>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has already been deleted.</exception>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectNotSavedException">Thrown when this object has not been initially saved yet.</exception>
		public void Delete(bool deleteContainerDatabase)
		{
			VerifyNotDeleted();
			if (_entity.Id == null)
			{
				throw new ObjectNotSavedException("Database Server has to be saved before it can be deleted.");
			}
			VerifyPermission("tmcontainer.delete");
			TranslationProviderServer.Service.DeleteContainer(_entity.Id, deleteContainerDatabase);
			DatabaseServer.DeleteContainer(this);
			_entity = null;
		}

		/// <summary>
		/// Saves this container.
		/// </summary>
		/// <exception cref="T:Sdl.LanguagePlatform.TranslationMemoryApi.ObjectDeletedException">Thrown when this object has already been deleted.</exception>
		public void Save()
		{
			VerifyNotDeleted();
			if (string.IsNullOrEmpty(_entity.DatabaseName))
			{
				throw new NullPropertyException("Container has no DatabaseName.");
			}
			if (string.IsNullOrEmpty(_entity.Name))
			{
				throw new NullPropertyException("Container has no name.");
			}
			if (_entity.DatabaseServer.ForeignKey == null)
			{
				throw new NullPropertyException("DatabaseServer does not exist for this Container.");
			}
			if (IsNewObject)
			{
				_entity = TranslationProviderServer.Service.CreateContainer(_entity, ParentResourceGroupPath);
				DatabaseServer.AddContainer(this);
			}
			else
			{
				VerifyPermission("tmcontainer.edit");
				_entity = TranslationProviderServer.Service.UpdateContainer(_entity);
			}
		}

		/// <summary>
		/// Gets whether this object has the permission with the specified name.
		/// </summary>
		/// <param name="permission">The permission name.</param>
		/// <returns>
		/// 	<code>true</code> is the object has the specified permission.
		/// </returns>
		public bool HasPermission(string permission)
		{
			VerifyNotDeleted();
			if (_entity.Permissions != null)
			{
				return _entity.Permissions.HasPermission(permission);
			}
			return true;
		}

		private void VerifyNotDeleted()
		{
			VerifyNotDeleted("The container has been deleted.");
		}

		private void VerifyNotDeleted(string message)
		{
			if (IsDeleted)
			{
				throw new ObjectDeletedException(message);
			}
		}

		private void VerifyPermission(string permission)
		{
			if (!HasPermission(permission))
			{
				throw new SecurityException($"Current user does not have {permission} permission on this container.");
			}
		}

		void IEditableObject.BeginEdit()
		{
			if (_entity != null && _backupEntity == null)
			{
				_backupEntity = new ContainerEntity();
				_backupEntity.Id = _entity.Id;
				_backupEntity.Name = _entity.Name;
				_backupEntity.Description = _entity.Description;
				_backupEntity.UniqueId = _entity.UniqueId;
				_backupEntity.DatabaseName = _entity.DatabaseName;
				_backupEntity.DatabaseServer = new EntityReference<DatabaseServerEntity>(_entity.DatabaseServer.ForeignKey);
				_backupEntity.MarkAsClean();
			}
		}

		/// <summary>
		/// Discards changes since the last <see cref="M:System.ComponentModel.IEditableObject.BeginEdit" /> call.
		/// </summary>
		void IEditableObject.CancelEdit()
		{
			if (_entity != null && _backupEntity != null)
			{
				Entity = _backupEntity;
				_backupEntity = null;
			}
		}

		/// <summary>
		/// Pushes changes since the last <see cref="M:System.ComponentModel.IEditableObject.BeginEdit" /> or <see cref="M:System.ComponentModel.IBindingList.AddNew" /> call into the underlying object.
		/// </summary>
		void IEditableObject.EndEdit()
		{
			_backupEntity = null;
		}

		private void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		/// <summary>
		/// Indicates whether the current object is equal to another object of the same type.
		/// </summary>
		/// <param name="other">An object to compare with this object.</param>
		/// <returns>
		/// true if the current object is equal to the <paramref name="other" /> parameter; otherwise, false.
		/// </returns>
		public bool Equals(TranslationMemoryContainer other)
		{
			return Id == other.Id;
		}

		/// <summary>
		/// Determines whether the specified <see cref="T:System.Object" /> is equal to this instance.
		/// </summary>
		/// <param name="obj">The <see cref="T:System.Object" /> to compare with this instance.</param>
		/// <returns>
		/// 	<c>true</c> if the specified <see cref="T:System.Object" /> is equal to this instance; otherwise, <c>false</c>.
		/// </returns>
		/// <exception cref="T:System.NullReferenceException">
		/// The <paramref name="obj" /> parameter is null.
		/// </exception>
		public override bool Equals(object obj)
		{
			TranslationMemoryContainer translationMemoryContainer = (TranslationMemoryContainer)obj;
			if (translationMemoryContainer != null)
			{
				return Equals(translationMemoryContainer);
			}
			return false;
		}

		/// <summary>
		/// Returns a hash code for this instance.
		/// </summary>
		/// <returns>
		/// A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. 
		/// </returns>
		public override int GetHashCode()
		{
			return Id.GetHashCode();
		}
	}
}
