using System.Runtime.Serialization;

namespace Sdl.LanguagePlatform.Core
{
	[DataContract]
	public enum ErrorCode
	{
		[EnumMember]
		OK,
		[EnumMember]
		System,
		[EnumMember]
		StorageError,
		[EnumMember]
		EmptySourceSegment,
		[EnumMember]
		InvalidSourceSegment,
		[EnumMember]
		EmptyTargetSegment,
		[EnumMember]
		InvalidTargetSegment,
		[EnumMember]
		SourceLanguageIncompatibleWithTM,
		[EnumMember]
		TargetLanguageIncompatibleWithTM,
		[EnumMember]
		Other,
		[EnumMember]
		UndefinedOrInvalidLanguage,
		[EnumMember]
		NeutralLanguage,
		[EnumMember]
		EmptySegment,
		[EnumMember]
		InvalidSegment,
		[EnumMember]
		InvalidSegmentPeripheralWhitespace,
		[EnumMember]
		NoTextInSegment,
		[EnumMember]
		TagInvalidTagAnchor,
		[EnumMember]
		TagEmptyOrInvalidTagID,
		[EnumMember]
		TagAnchorAlreadyUsed,
		[EnumMember]
		TagAnchorNotOpen,
		[EnumMember]
		TagAnchorAlreadyClosed,
		[EnumMember]
		TagAnchorNotClosed,
		[EnumMember]
		TagWarningTagsDropped,
		[EnumMember]
		NotImplemented,
		[EnumMember]
		TMNotFound,
		[EnumMember]
		TMOrContainerMissing,
		[EnumMember]
		SegmentationUnknownVariable,
		[EnumMember]
		SegmentationNoRulesForLanguage,
		[EnumMember]
		SegmentationRuleDeserializationError,
		[EnumMember]
		SegmentationRuleLoadError,
		[EnumMember]
		SegmentationEmptyRuleSet,
		[EnumMember]
		SegmentationIllegalKeywordInRule,
		[EnumMember]
		SegmentationIllegalContinuation,
		[EnumMember]
		SegmentationTrailingJunk,
		[EnumMember]
		SegmentationUnknownRuleType,
		[EnumMember]
		SegmentationInvalidVariableName,
		[EnumMember]
		SegmentationInvalidRule,
		[EnumMember]
		SegmentationCannotObtainSegmentor,
		[EnumMember]
		SegmentationSRXParseError,
		[EnumMember]
		SegmentationSRXNoVersion,
		[EnumMember]
		SegmentationSRXUnsupportedVersion,
		[EnumMember]
		SegmentationSRXInternalError,
		[EnumMember]
		SegmentationSRXInvalidDocument,
		[EnumMember]
		SegmentationTWBMalformedRule,
		[EnumMember]
		SegmentationTWBUnsupportedNestedExceptions,
		[EnumMember]
		SegmentationTWBUnsupportedExceptionConstraints,
		[EnumMember]
		SegmentationTWBUnsupportedMultipleMatchContexts,
		[EnumMember]
		ConfigurationCannotLoad,
		[EnumMember]
		ConfigurationCannotResolveType,
		[EnumMember]
		ConfigurationInvalidType,
		[EnumMember]
		ConfigurationAbstractType,
		[EnumMember]
		ConfigurationCannotInstantiateOrCastType,
		[EnumMember]
		ConfigurationConnectionStringNotFound,
		[EnumMember]
		ConfigurationUnknownProviderType,
		[EnumMember]
		ConfigurationOtherError,
		[EnumMember]
		AuthInsufficientPermissions,
		[EnumMember]
		AuthUnknownOrNonauthenticatedUser,
		[EnumMember]
		AuthInvalidUser,
		[EnumMember]
		TMInvalidFieldName,
		[EnumMember]
		TMInvalidPicklistValueName,
		[EnumMember]
		TMInvalidTMName,
		[EnumMember]
		TMExceededTMNameLimit,
		[EnumMember]
		TMExceededFieldNameLimit,
		[EnumMember]
		TMExceededPicklistValueNameLimit,
		[EnumMember]
		TMExceededCopyrightFieldLimit,
		[EnumMember]
		TMExceededDescriptionFieldLimit,
		[EnumMember]
		TMExceededTextFieldValueLimit,
		[EnumMember]
		TMAlreadyExists,
		[EnumMember]
		DAFieldTypesInconsistent,
		[EnumMember]
		InvalidTMSourceLanguage,
		[EnumMember]
		InvalidTMTargetLanguage,
		[EnumMember]
		DATUNotInTM,
		[EnumMember]
		DAInvalidSegmentAfterDeserialization,
		[EnumMember]
		DAIndexDuplicateKey,
		[EnumMember]
		TMInvalidIteratorSize,
		[EnumMember]
		TMUndefinedCascadeElement,
		[EnumMember]
		TMUninitializedCascadeElement,
		[EnumMember]
		TMUndefinedTMInCascade,
		[EnumMember]
		TMUninitializedTMInCascade,
		[EnumMember]
		TMCannotInitializeTMInCascade,
		[EnumMember]
		TMIncompatibleTMLanguageDirectionInCascade,
		[EnumMember]
		TMIncompatibleFieldTypes,
		[EnumMember]
		TMInvalidSortSpecification,
		[EnumMember]
		TMNoTMOpen,
		[EnumMember]
		TMFieldAlreadyExists,
		[EnumMember]
		TMPicklistValueAlreadyExists,
		[EnumMember]
		TMResourceAlreadyExists,
		[EnumMember]
		TMResourceDoesNotExist,
		[EnumMember]
		TMSourceLanguageMismatch,
		[EnumMember]
		TMTargetLanguageMismatch,
		[EnumMember]
		TMCannotModifyExactSearchOnlyFlag,
		[EnumMember]
		TMSearchModeNotSupported,
		[EnumMember]
		TMCannotModifyFullTextSearchFlag,
		[EnumMember]
		TMCannotModifyFuzzyIndices,
		[EnumMember]
		TMImportFieldNotExists,
		[EnumMember]
		TMImportIncompatibleFieldTypes,
		[EnumMember]
		TMTULimitExceeded,
		[EnumMember]
		StorageTMAlreadyExists,
		[EnumMember]
		StorageSchemaDoesntExist,
		[EnumMember]
		StorageSchemaAlreadyExists,
		[EnumMember]
		StoragePicklistValueAlreadyExists,
		[EnumMember]
		StorageIncompatibleAttributeType,
		[EnumMember]
		StorageFieldNotFound,
		[EnumMember]
		StorageFieldAlreadyExists,
		[EnumMember]
		StorageParameterNotFound,
		[EnumMember]
		StorageDataFileNotFound,
		[EnumMember]
		StorageVersionDataOutdated,
		[EnumMember]
		StorageVersionDataNewer,
		[EnumMember]
		TMXUnknownVersion,
		[EnumMember]
		TMXNoSegmentOpen,
		[EnumMember]
		TMXUnknownTMXAttribute,
		[EnumMember]
		TMXMissingVersion,
		[EnumMember]
		TMXCannotAddTagData,
		[EnumMember]
		TMXInternalParserError,
		[EnumMember]
		TMXUnexpectedInputData,
		[EnumMember]
		TMXCannotDetermineLanguageDirection,
		[EnumMember]
		StemmerErrorInStemmingRule,
		[EnumMember]
		TokenizerInvalidNumericFormat,
		[EnumMember]
		TokenizerInvalidCharacterSet,
		[EnumMember]
		NoRegionSpecificLanguageFound,
		[EnumMember]
		ErrorInFilterExpression,
		[EnumMember]
		ErrorFilterUnbalancedParenthesis,
		[EnumMember]
		ErrorFilterExpectFieldName,
		[EnumMember]
		ErrorFilterInvalidFieldName,
		[EnumMember]
		ErrorFilterEmptyFieldName,
		[EnumMember]
		ErrorFilterUnknownField,
		[EnumMember]
		ErrorFilterPrematureEndOfInput,
		[EnumMember]
		ErrorFilterOperatorExpected,
		[EnumMember]
		ErrorFilterNotAPicklistField,
		[EnumMember]
		ErrorFilterPicklistItemNotFound,
		[EnumMember]
		ErrorFilterFieldNameNotSurroundedByDoubleQuotes,
		[EnumMember]
		ErrorFilterMultipleValuesNotBracketed,
		[EnumMember]
		ErrorFilterMultivalueFieldNotBracketed,
		[EnumMember]
		ErrorFilterFieldRequiresIntegerValue,
		[EnumMember]
		ErrorFilterValueNotSurroundedByDoubleQuotes,
		[EnumMember]
		ErrorFilterCannotParseDate,
		[EnumMember]
		ErrorFilterTrailingBackslash,
		[EnumMember]
		ErrorFilterIllegalInputSymbol,
		[EnumMember]
		ErrorFilterTrailingJunk,
		[EnumMember]
		TMToolsNoTM,
		[EnumMember]
		TMToolsNoFileHeader,
		[EnumMember]
		TMToolsIncompatibleLanguagesBetweenDocumentAndTM,
		[EnumMember]
		InternalError,
		[EnumMember]
		CorruptData,
		[EnumMember]
		InconsistentData,
		[EnumMember]
		CannotInitializeSpring,
		[EnumMember]
		CannotInitializeFilterManager,
		[EnumMember]
		InvalidOperation,
		[EnumMember]
		ReadonlyResource,
		[EnumMember]
		EmbeddedResourceNotFound,
		[EnumMember]
		ResourceNotAvailable,
		[EnumMember]
		DataComponentMissing,
		[EnumMember]
		DataComponentIncompatible,
		[EnumMember]
		DataComponentNotOpen,
		[EnumMember]
		DataComponentAlreadyInUse,
		[EnumMember]
		SegmentNotTokenized,
		[EnumMember]
		TagCountLimitExceeded,
		[EnumMember]
		NoTranslatableContentInFile,
		[EnumMember]
		NoContentInFile,
		[EnumMember]
		UnexpectedDocumentContent,
		[EnumMember]
		LanguageResourceFileNotFound,
		[EnumMember]
		InvalidLanguageResourceFile,
		[EnumMember]
		CorruptDataInResourceFile,
		[EnumMember]
		XmlError,
		[EnumMember]
		EditScriptEmptySearchPattern,
		[EnumMember]
		EditScriptEmptyFieldName,
		[EnumMember]
		EditScriptSystemField,
		[EnumMember]
		EditScriptIncompatibleFieldValueTypes,
		[EnumMember]
		EditScriptInvalidValue,
		[EnumMember]
		EditScriptIncompatibleField,
		[EnumMember]
		EditScriptInvalidOperationForFieldValueType,
		[EnumMember]
		SQLiteNotADatabase,
		[EnumMember]
		SQLiteCorrupt,
		[EnumMember]
		SQLiteOtherError,
		[EnumMember]
		EmptyData
	}
}
