using System.Collections.Generic;

namespace Sdl.LanguagePlatform.IO.TMX
{
	internal class EntityMappings
	{
		private static Dictionary<string, char> _MappedEntities;

		static EntityMappings()
		{
			_MappedEntities = new Dictionary<string, char>();
			AddISOLAT1EntitySet();
			AddISOLAT2EntitySet();
			AddISONUMEntitySet();
			AddISOPUBEntitySet();
			AddISOTECHEntitySet();
			AddHTMLSPECIALEntitySet();
			AddHTMLSYMBOLEntitySet();
		}

		public static bool GetMapping(string entityName, out char unicodeEquivalent)
		{
			unicodeEquivalent = '\0';
			return _MappedEntities.TryGetValue(entityName, out unicodeEquivalent);
		}

		private static void AddEntityMapping(string name, char unicodeEquivalent)
		{
			AddEntityMapping(name, unicodeEquivalent, active: true);
		}

		private static void AddEntityMapping(string name, char unicodeEquivalent, bool active)
		{
			if (active && !_MappedEntities.TryGetValue(name, out char _))
			{
				_MappedEntities.Add(name, unicodeEquivalent);
			}
		}

		private static void AddISODIAEntitySet()
		{
			AddEntityMapping("acute", '\u00b4');
			AddEntityMapping("breve", '\u02d8');
			AddEntityMapping("caron", '\u02c7');
			AddEntityMapping("cedil", '\u00b8');
			AddEntityMapping("circ", '\u02c6');
			AddEntityMapping("dblac", '\u02dd');
			AddEntityMapping("die", '\u00a8');
			AddEntityMapping("dot", '\u02d9');
			AddEntityMapping("grave", '`');
			AddEntityMapping("macr", '\u00af');
			AddEntityMapping("ogon", '\u02db');
			AddEntityMapping("ring", '\u02da');
			AddEntityMapping("tilde", '\u02dc');
			AddEntityMapping("uml", '\u00a8');
		}

		private static void AddISOLAT1EntitySet()
		{
			AddEntityMapping("AElig", 'Æ');
			AddEntityMapping("Aacute", 'Á');
			AddEntityMapping("Acirc", 'Â');
			AddEntityMapping("Agrave", 'À');
			AddEntityMapping("Aring", 'Å');
			AddEntityMapping("Atilde", 'Ã');
			AddEntityMapping("Auml", 'Ä');
			AddEntityMapping("Ccedil", 'Ç');
			AddEntityMapping("ETH", 'Ð');
			AddEntityMapping("Eacute", 'É');
			AddEntityMapping("Ecirc", 'Ê');
			AddEntityMapping("Egrave", 'È');
			AddEntityMapping("Euml", 'Ë');
			AddEntityMapping("Iacute", 'Í');
			AddEntityMapping("Icirc", 'Î');
			AddEntityMapping("Igrave", 'Ì');
			AddEntityMapping("Iuml", 'Ï');
			AddEntityMapping("Ntilde", 'Ñ');
			AddEntityMapping("Oacute", 'Ó');
			AddEntityMapping("Ocirc", 'Ô');
			AddEntityMapping("Ograve", 'Ò');
			AddEntityMapping("Oslash", 'Ø');
			AddEntityMapping("Otilde", 'Õ');
			AddEntityMapping("Ouml", 'Ö');
			AddEntityMapping("THORN", 'Þ');
			AddEntityMapping("Uacute", 'Ú');
			AddEntityMapping("Ucirc", 'Û');
			AddEntityMapping("Ugrave", 'Ù');
			AddEntityMapping("Uuml", 'Ü');
			AddEntityMapping("Yacute", 'Ý');
			AddEntityMapping("aacute", 'á');
			AddEntityMapping("acirc", 'â');
			AddEntityMapping("aelig", 'æ');
			AddEntityMapping("agrave", 'à');
			AddEntityMapping("aring", 'å');
			AddEntityMapping("atilde", 'ã');
			AddEntityMapping("auml", 'ä');
			AddEntityMapping("ccedil", 'ç');
			AddEntityMapping("eacute", 'é');
			AddEntityMapping("ecirc", 'ê');
			AddEntityMapping("egrave", 'è');
			AddEntityMapping("eth", 'ð');
			AddEntityMapping("euml", 'ë');
			AddEntityMapping("iacute", 'í');
			AddEntityMapping("icirc", 'î');
			AddEntityMapping("igrave", 'ì');
			AddEntityMapping("iuml", 'ï');
			AddEntityMapping("ntilde", 'ñ');
			AddEntityMapping("oacute", 'ó');
			AddEntityMapping("ocirc", 'ô');
			AddEntityMapping("ograve", 'ò');
			AddEntityMapping("oslash", 'ø');
			AddEntityMapping("otilde", 'õ');
			AddEntityMapping("ouml", 'ö');
			AddEntityMapping("szlig", 'ß');
			AddEntityMapping("thorn", 'þ');
			AddEntityMapping("uacute", 'ú');
			AddEntityMapping("ucirc", 'û');
			AddEntityMapping("ugrave", 'ù');
			AddEntityMapping("uuml", 'ü');
			AddEntityMapping("yacute", 'ý');
			AddEntityMapping("yuml", 'ÿ', active: true);
		}

		private static void AddISOLAT2EntitySet()
		{
			AddEntityMapping("Abreve", 'Ă');
			AddEntityMapping("Amacr", 'Ā');
			AddEntityMapping("Aogon", 'Ą');
			AddEntityMapping("Cacute", 'Ć');
			AddEntityMapping("Ccaron", 'Č');
			AddEntityMapping("Ccirc", 'Ĉ');
			AddEntityMapping("Cdot", 'Ċ');
			AddEntityMapping("Dcaron", 'Ď');
			AddEntityMapping("Dstrok", 'Đ');
			AddEntityMapping("ENG", 'Ŋ');
			AddEntityMapping("Ecaron", 'Ě');
			AddEntityMapping("Edot", 'Ė');
			AddEntityMapping("Emacr", 'Ē');
			AddEntityMapping("Eogon", 'Ę');
			AddEntityMapping("Gbreve", 'Ğ');
			AddEntityMapping("Gcedil", 'Ģ');
			AddEntityMapping("Gcirc", 'Ĝ');
			AddEntityMapping("Gdot", 'Ġ');
			AddEntityMapping("Hcirc", 'Ĥ');
			AddEntityMapping("Hstrok", 'Ħ');
			AddEntityMapping("IJlig", 'Ĳ');
			AddEntityMapping("Idot", 'İ');
			AddEntityMapping("Imacr", 'Ī');
			AddEntityMapping("Iogon", 'Į');
			AddEntityMapping("Itilde", 'Ĩ');
			AddEntityMapping("Jcirc", 'Ĵ');
			AddEntityMapping("Kcedil", 'Ķ');
			AddEntityMapping("Lacute", 'Ĺ');
			AddEntityMapping("Lcaron", 'Ľ');
			AddEntityMapping("Lcedil", 'Ļ');
			AddEntityMapping("Lmidot", 'Ŀ');
			AddEntityMapping("Lstrok", 'Ł');
			AddEntityMapping("Nacute", 'Ń');
			AddEntityMapping("Ncaron", 'Ň');
			AddEntityMapping("Ncedil", 'Ņ');
			AddEntityMapping("OElig", 'Œ');
			AddEntityMapping("Odblac", 'Ő');
			AddEntityMapping("Omacr", 'Ō');
			AddEntityMapping("Racute", 'Ŕ');
			AddEntityMapping("Rcaron", 'Ř');
			AddEntityMapping("Rcedil", 'Ŗ');
			AddEntityMapping("Sacute", 'Ś');
			AddEntityMapping("Scaron", 'Š');
			AddEntityMapping("Scedil", 'Ş');
			AddEntityMapping("Scirc", 'Ŝ');
			AddEntityMapping("Tcaron", 'Ť');
			AddEntityMapping("Tcedil", 'Ţ');
			AddEntityMapping("Tstrok", 'Ŧ');
			AddEntityMapping("Ubreve", 'Ŭ');
			AddEntityMapping("Udblac", 'Ű');
			AddEntityMapping("Umacr", 'Ū');
			AddEntityMapping("Uogon", 'Ų');
			AddEntityMapping("Uring", 'Ů');
			AddEntityMapping("Utilde", 'Ũ');
			AddEntityMapping("Wcirc", 'Ŵ');
			AddEntityMapping("Ycirc", 'Ŷ');
			AddEntityMapping("Yuml", 'Ÿ');
			AddEntityMapping("Zacute", 'Ź');
			AddEntityMapping("Zcaron", 'Ž');
			AddEntityMapping("Zdot", 'Ż');
			AddEntityMapping("abreve", 'ă');
			AddEntityMapping("amacr", 'ā');
			AddEntityMapping("aogon", 'ą');
			AddEntityMapping("cacute", 'ć');
			AddEntityMapping("ccaron", 'č');
			AddEntityMapping("ccirc", 'ĉ');
			AddEntityMapping("cdot", 'ċ');
			AddEntityMapping("dcaron", 'ď');
			AddEntityMapping("dstrok", 'đ');
			AddEntityMapping("ecaron", 'ě');
			AddEntityMapping("edot", 'ė');
			AddEntityMapping("emacr", 'ē');
			AddEntityMapping("eng", 'ŋ');
			AddEntityMapping("eogon", 'ę');
			AddEntityMapping("gacute", 'ǵ');
			AddEntityMapping("gbreve", 'ğ');
			AddEntityMapping("gcirc", 'ĝ');
			AddEntityMapping("gdot", 'ġ');
			AddEntityMapping("hcirc", 'ĥ');
			AddEntityMapping("hstrok", 'ħ');
			AddEntityMapping("ijlig", 'ĳ');
			AddEntityMapping("imacr", 'ī');
			AddEntityMapping("inodot", 'ı');
			AddEntityMapping("iogon", 'į');
			AddEntityMapping("itilde", 'ĩ');
			AddEntityMapping("jcirc", 'ĵ');
			AddEntityMapping("kcedil", 'ķ');
			AddEntityMapping("kgreen", 'ĸ');
			AddEntityMapping("lacute", 'ĺ');
			AddEntityMapping("lcaron", 'ľ');
			AddEntityMapping("lcedil", 'ļ');
			AddEntityMapping("lmidot", 'ŀ');
			AddEntityMapping("lstrok", 'ł');
			AddEntityMapping("nacute", 'ń');
			AddEntityMapping("napos", 'ŉ');
			AddEntityMapping("ncaron", 'ň');
			AddEntityMapping("ncedil", 'ņ');
			AddEntityMapping("odblac", 'ő');
			AddEntityMapping("oelig", 'œ');
			AddEntityMapping("omacr", 'ō');
			AddEntityMapping("racute", 'ŕ');
			AddEntityMapping("rcaron", 'ř');
			AddEntityMapping("rcedil", 'ŗ');
			AddEntityMapping("sacute", 'ś');
			AddEntityMapping("scaron", 'š');
			AddEntityMapping("scedil", 'ş');
			AddEntityMapping("scirc", 'ŝ');
			AddEntityMapping("tcaron", 'ť');
			AddEntityMapping("tcedil", 'ţ');
			AddEntityMapping("tstrok", 'ŧ');
			AddEntityMapping("ubreve", 'ŭ');
			AddEntityMapping("udblac", 'ű');
			AddEntityMapping("umacr", 'ū');
			AddEntityMapping("uogon", 'ų');
			AddEntityMapping("uring", 'ů');
			AddEntityMapping("utilde", 'ũ');
			AddEntityMapping("wcirc", 'ŵ');
			AddEntityMapping("ycirc", 'ŷ');
			AddEntityMapping("zacute", 'ź');
			AddEntityMapping("zcaron", 'ž');
			AddEntityMapping("zdot", 'ż', active: true);
		}

		private static void AddISONUMEntitySet()
		{
			AddEntityMapping("amp", '&');
			AddEntityMapping("apos", '\'');
			AddEntityMapping("ast", '*');
			AddEntityMapping("brvbar", '¦');
			AddEntityMapping("bsol", '\\');
			AddEntityMapping("cent", '¢');
			AddEntityMapping("colon", ':');
			AddEntityMapping("comma", ',');
			AddEntityMapping("commat", '@');
			AddEntityMapping("copy", '©');
			AddEntityMapping("curren", '¤');
			AddEntityMapping("darr", '↓');
			AddEntityMapping("deg", '°');
			AddEntityMapping("divide", '÷');
			AddEntityMapping("dollar", '$');
			AddEntityMapping("equals", '=');
			AddEntityMapping("excl", '!');
			AddEntityMapping("frac12", '½');
			AddEntityMapping("frac14", '¼');
			AddEntityMapping("frac18", '⅛');
			AddEntityMapping("frac34", '¾');
			AddEntityMapping("frac38", '⅜');
			AddEntityMapping("frac58", '⅝');
			AddEntityMapping("frac78", '⅞');
			AddEntityMapping("gt", '>');
			AddEntityMapping("half", '½');
			AddEntityMapping("horbar", '―');
			AddEntityMapping("hyphen", '‐');
			AddEntityMapping("iexcl", '¡');
			AddEntityMapping("iquest", '¿');
			AddEntityMapping("laquo", '«');
			AddEntityMapping("larr", '←');
			AddEntityMapping("lcub", '{');
			AddEntityMapping("ldquo", '“');
			AddEntityMapping("lowbar", '_');
			AddEntityMapping("lpar", '(');
			AddEntityMapping("lsqb", '[');
			AddEntityMapping("lsquo", '‘');
			AddEntityMapping("lt", '<');
			AddEntityMapping("micro", 'µ');
			AddEntityMapping("middot", '·');
			AddEntityMapping("nbsp", '\u00a0');
			AddEntityMapping("not", '¬');
			AddEntityMapping("num", '#');
			AddEntityMapping("ohm", 'Ω');
			AddEntityMapping("ordf", 'ª');
			AddEntityMapping("ordm", 'º');
			AddEntityMapping("para", '¶');
			AddEntityMapping("percnt", '%');
			AddEntityMapping("period", '.');
			AddEntityMapping("plus", '+');
			AddEntityMapping("plusmn", '±');
			AddEntityMapping("pound", '£');
			AddEntityMapping("quest", '?');
			AddEntityMapping("quot", '"');
			AddEntityMapping("raquo", '»');
			AddEntityMapping("rarr", '→');
			AddEntityMapping("rcub", '}');
			AddEntityMapping("rdquo", '”');
			AddEntityMapping("reg", '®');
			AddEntityMapping("rpar", ')');
			AddEntityMapping("rsqb", ']');
			AddEntityMapping("rsquo", '’');
			AddEntityMapping("sect", '§');
			AddEntityMapping("semi", ';');
			AddEntityMapping("shy", '­');
			AddEntityMapping("sol", '/');
			AddEntityMapping("sung", '♪');
			AddEntityMapping("sup1", '¹');
			AddEntityMapping("sup2", '²');
			AddEntityMapping("sup3", '³');
			AddEntityMapping("times", '×');
			AddEntityMapping("trade", '™');
			AddEntityMapping("uarr", '↑');
			AddEntityMapping("verbar", '|');
			AddEntityMapping("yen", '¥', active: true);
		}

		private static void AddISOPUBEntitySet()
		{
			AddEntityMapping("Dagger", '‡');
			AddEntityMapping("blank", '␣');
			AddEntityMapping("blk12", '▒');
			AddEntityMapping("blk14", '░');
			AddEntityMapping("blk34", '▓');
			AddEntityMapping("block", '█');
			AddEntityMapping("bull", '•');
			AddEntityMapping("caret", '⁁');
			AddEntityMapping("check", '✓');
			AddEntityMapping("cir", '○');
			AddEntityMapping("clubs", '♣');
			AddEntityMapping("copysr", '℗');
			AddEntityMapping("cross", '✗');
			AddEntityMapping("dagger", '†');
			AddEntityMapping("dash", '‐');
			AddEntityMapping("diams", '♦');
			AddEntityMapping("dlcrop", '⌍');
			AddEntityMapping("drcrop", '⌌');
			AddEntityMapping("dtri", '▿');
			AddEntityMapping("dtrif", '▾');
			AddEntityMapping("emsp", '\u2003');
			AddEntityMapping("emsp13", '\u2004');
			AddEntityMapping("emsp14", '\u2005');
			AddEntityMapping("ensp", '\u2002');
			AddEntityMapping("female", '♀');
			AddEntityMapping("ffilig", 'ﬃ');
			AddEntityMapping("fflig", 'ﬀ');
			AddEntityMapping("ffllig", 'ﬄ');
			AddEntityMapping("filig", 'ﬁ');
			AddEntityMapping("fjlig", 'f', active: false);
			AddEntityMapping("flat", '♭');
			AddEntityMapping("fllig", 'ﬂ');
			AddEntityMapping("frac13", '⅓');
			AddEntityMapping("frac15", '⅕');
			AddEntityMapping("frac16", '⅙');
			AddEntityMapping("frac23", '⅔');
			AddEntityMapping("frac25", '⅖');
			AddEntityMapping("frac35", '⅗');
			AddEntityMapping("frac45", '⅘');
			AddEntityMapping("frac56", '⅚');
			AddEntityMapping("hairsp", '\u200a');
			AddEntityMapping("hearts", '♥');
			AddEntityMapping("hellip", '…');
			AddEntityMapping("hybull", '⁃');
			AddEntityMapping("incare", '℅');
			AddEntityMapping("ldquor", '„');
			AddEntityMapping("lhblk", '▄');
			AddEntityMapping("loz", '◊');
			AddEntityMapping("lozf", '⧫');
			AddEntityMapping("lsquor", '‚');
			AddEntityMapping("ltri", '◃');
			AddEntityMapping("ltrif", '◂');
			AddEntityMapping("male", '♂');
			AddEntityMapping("malt", '✠');
			AddEntityMapping("marker", '▮');
			AddEntityMapping("mdash", '—');
			AddEntityMapping("mldr", '…');
			AddEntityMapping("natur", '♮');
			AddEntityMapping("ndash", '–');
			AddEntityMapping("nldr", '‥');
			AddEntityMapping("numsp", '\u2007');
			AddEntityMapping("phone", '☎');
			AddEntityMapping("puncsp", '\u2008');
			AddEntityMapping("rdquor", '”');
			AddEntityMapping("rect", '▭');
			AddEntityMapping("rsquor", '’');
			AddEntityMapping("rtri", '▹');
			AddEntityMapping("rtrif", '▸');
			AddEntityMapping("rx", '℞');
			AddEntityMapping("sext", '✶');
			AddEntityMapping("sharp", '♯');
			AddEntityMapping("spades", '♠');
			AddEntityMapping("squ", '□');
			AddEntityMapping("squf", '▪');
			AddEntityMapping("star", '☆');
			AddEntityMapping("starf", '★');
			AddEntityMapping("target", '⌖');
			AddEntityMapping("telrec", '⌕');
			AddEntityMapping("thinsp", '\u2009');
			AddEntityMapping("uhblk", '▀');
			AddEntityMapping("ulcrop", '⌏');
			AddEntityMapping("urcrop", '⌎');
			AddEntityMapping("utri", '▵');
			AddEntityMapping("utrif", '▴');
			AddEntityMapping("vellip", '⋮');
		}

		private static void AddISOTECHEntitySet()
		{
			AddEntityMapping("And", '⩓');
			AddEntityMapping("Cconint", '∰');
			AddEntityMapping("Conint", '∯');
			AddEntityMapping("Dot", '\u00a8');
			AddEntityMapping("DotDot", '\u20dc');
			AddEntityMapping("Int", '∬');
			AddEntityMapping("Lang", '⟪');
			AddEntityMapping("Not", '⫬');
			AddEntityMapping("Or", '⩔');
			AddEntityMapping("Prime", '″');
			AddEntityMapping("Rang", '⟫');
			AddEntityMapping("Verbar", '‖');
			AddEntityMapping("acd", '∿');
			AddEntityMapping("aleph", 'ℵ');
			AddEntityMapping("and", '∧');
			AddEntityMapping("andand", '⩕');
			AddEntityMapping("andd", '⩜');
			AddEntityMapping("andslope", '⩘');
			AddEntityMapping("andv", '⩚');
			AddEntityMapping("angrt", '∟');
			AddEntityMapping("angsph", '∢');
			AddEntityMapping("angst", 'Å');
			AddEntityMapping("ap", '≈');
			AddEntityMapping("apacir", '⩯');
			AddEntityMapping("awconint", '∳');
			AddEntityMapping("awint", '⨑');
			AddEntityMapping("bNot", '⫭');
			AddEntityMapping("becaus", '∵');
			AddEntityMapping("bernou", 'ℬ');
			AddEntityMapping("bne", '=', active: false);
			AddEntityMapping("bnequiv", '≡', active: false);
			AddEntityMapping("bnot", '⌐');
			AddEntityMapping("bottom", '⊥');
			AddEntityMapping("cap", '∩');
			AddEntityMapping("cirfnint", '⨐');
			AddEntityMapping("compfn", '∘');
			AddEntityMapping("cong", '≅');
			AddEntityMapping("conint", '∮');
			AddEntityMapping("ctdot", '⋯');
			AddEntityMapping("cup", '∪');
			AddEntityMapping("cwconint", '∲');
			AddEntityMapping("cwint", '∱');
			AddEntityMapping("cylcty", '⌭');
			AddEntityMapping("disin", '⋲');
			AddEntityMapping("dsol", '⧶');
			AddEntityMapping("dtdot", '⋱');
			AddEntityMapping("dwangle", '⦦');
			AddEntityMapping("elinters", '⏧');
			AddEntityMapping("epar", '⋕');
			AddEntityMapping("eparsl", '⧣');
			AddEntityMapping("equiv", '≡');
			AddEntityMapping("eqvparsl", '⧥');
			AddEntityMapping("exist", '∃');
			AddEntityMapping("fltns", '▱');
			AddEntityMapping("fnof", 'ƒ');
			AddEntityMapping("forall", '∀');
			AddEntityMapping("fpartint", '⨍');
			AddEntityMapping("ge", '≥');
			AddEntityMapping("hamilt", 'ℋ');
			AddEntityMapping("iff", '⇔');
			AddEntityMapping("iinfin", '⧜');
			AddEntityMapping("imped", 'Ƶ');
			AddEntityMapping("infin", '∞');
			AddEntityMapping("infintie", '⧝');
			AddEntityMapping("int", '∫');
			AddEntityMapping("intlarhk", '⨗');
			AddEntityMapping("isin", '∈');
			AddEntityMapping("isinE", '⋹');
			AddEntityMapping("isindot", '⋵');
			AddEntityMapping("isins", '⋴');
			AddEntityMapping("isinsv", '⋳');
			AddEntityMapping("isinv", '∈');
			AddEntityMapping("lArr", '⇐');
			AddEntityMapping("lagran", 'ℒ');
			AddEntityMapping("lang", '〈');
			AddEntityMapping("lbbrk", '⦗');
			AddEntityMapping("le", '≤');
			AddEntityMapping("loang", '⟬');
			AddEntityMapping("lobrk", '⟦');
			AddEntityMapping("lopar", '⦅');
			AddEntityMapping("lowast", '∗');
			AddEntityMapping("minus", '−');
			AddEntityMapping("mnplus", '∓');
			AddEntityMapping("nabla", '∇');
			AddEntityMapping("ne", '≠');
			AddEntityMapping("nedot", '≐', active: false);
			AddEntityMapping("nhpar", '⫲');
			AddEntityMapping("ni", '∋');
			AddEntityMapping("nis", '⋼');
			AddEntityMapping("nisd", '⋺');
			AddEntityMapping("niv", '∋');
			AddEntityMapping("notin", '∉');
			AddEntityMapping("notinE", '⋹', active: false);
			AddEntityMapping("notindot", '⋵', active: false);
			AddEntityMapping("notinva", '∉');
			AddEntityMapping("notinvb", '⋷');
			AddEntityMapping("notinvc", '⋶');
			AddEntityMapping("notni", '∌');
			AddEntityMapping("notniva", '∌');
			AddEntityMapping("notnivb", '⋾');
			AddEntityMapping("notnivc", '⋽');
			AddEntityMapping("nparsl", '⫽', active: false);
			AddEntityMapping("npart", '∂', active: false);
			AddEntityMapping("npolint", '⨔');
			AddEntityMapping("nvinfin", '⧞');
			AddEntityMapping("olcross", '⦻');
			AddEntityMapping("or", '∨');
			AddEntityMapping("ord", '⩝');
			AddEntityMapping("order", 'ℴ');
			AddEntityMapping("oror", '⩖');
			AddEntityMapping("orslope", '⩗');
			AddEntityMapping("orv", '⩛');
			AddEntityMapping("par", '∥');
			AddEntityMapping("parsl", '⫽');
			AddEntityMapping("part", '∂');
			AddEntityMapping("permil", '‰');
			AddEntityMapping("perp", '⊥');
			AddEntityMapping("pertenk", '‱');
			AddEntityMapping("phmmat", 'ℳ');
			AddEntityMapping("pointint", '⨕');
			AddEntityMapping("prime", '′');
			AddEntityMapping("profalar", '⌮');
			AddEntityMapping("profline", '⌒');
			AddEntityMapping("profsurf", '⌓');
			AddEntityMapping("prop", '∝');
			AddEntityMapping("qint", '⨌');
			AddEntityMapping("qprime", '⁗');
			AddEntityMapping("quatint", '⨖');
			AddEntityMapping("rArr", '⇒');
			AddEntityMapping("radic", '√');
			AddEntityMapping("rang", '〉');
			AddEntityMapping("rbbrk", '⦘');
			AddEntityMapping("roang", '⟭');
			AddEntityMapping("robrk", '⟧');
			AddEntityMapping("ropar", '⦆');
			AddEntityMapping("rppolint", '⨒');
			AddEntityMapping("scpolint", '⨓');
			AddEntityMapping("sim", '∼');
			AddEntityMapping("simdot", '⩪');
			AddEntityMapping("sime", '≃');
			AddEntityMapping("smeparsl", '⧤');
			AddEntityMapping("square", '□');
			AddEntityMapping("squarf", '▪');
			AddEntityMapping("strns", '\u00af');
			AddEntityMapping("sub", '⊂');
			AddEntityMapping("sube", '⊆');
			AddEntityMapping("sup", '⊃');
			AddEntityMapping("supe", '⊇');
			AddEntityMapping("tdot", '\u20db');
			AddEntityMapping("there4", '∴');
			AddEntityMapping("tint", '∭');
			AddEntityMapping("top", '⊤');
			AddEntityMapping("topbot", '⌶');
			AddEntityMapping("topcir", '⫱');
			AddEntityMapping("tprime", '‴');
			AddEntityMapping("utdot", '⋰');
			AddEntityMapping("uwangle", '⦧');
			AddEntityMapping("vangrt", '⦜');
			AddEntityMapping("veeeq", '≚');
			AddEntityMapping("wedgeq", '≙');
			AddEntityMapping("xnis", '⋻');
		}

		private static void AddHTMLSPECIALEntitySet()
		{
			AddEntityMapping("Dagger", '‡');
			AddEntityMapping("OElig", 'Œ');
			AddEntityMapping("Scaron", 'Š');
			AddEntityMapping("Yuml", 'Ÿ');
			AddEntityMapping("amp", '&');
			AddEntityMapping("bdquo", '„');
			AddEntityMapping("circ", '\u02c6');
			AddEntityMapping("dagger", '†');
			AddEntityMapping("emsp", '\u2003');
			AddEntityMapping("ensp", '\u2002');
			AddEntityMapping("gt", '>');
			AddEntityMapping("ldquo", '“');
			AddEntityMapping("lrm", '\u200e');
			AddEntityMapping("lsaquo", '‹');
			AddEntityMapping("lsquo", '‘');
			AddEntityMapping("lt", '<');
			AddEntityMapping("mdash", '—');
			AddEntityMapping("nbsp", '\u00a0');
			AddEntityMapping("ndash", '–');
			AddEntityMapping("oelig", 'œ');
			AddEntityMapping("permil", '‰');
			AddEntityMapping("quot", '"');
			AddEntityMapping("rdquo", '”');
			AddEntityMapping("rlm", '\u200f');
			AddEntityMapping("rsaquo", '›');
			AddEntityMapping("rsquo", '’');
			AddEntityMapping("sbquo", '‚');
			AddEntityMapping("scaron", 'š');
			AddEntityMapping("thinsp", '\u2009');
			AddEntityMapping("tilde", '\u02dc');
			AddEntityMapping("zwj", '\u200d');
			AddEntityMapping("zwnj", '\u200c');
		}

		private static void AddHTMLSYMBOLEntitySet()
		{
			AddEntityMapping("Alpha", 'Α');
			AddEntityMapping("Beta", 'Β');
			AddEntityMapping("Chi", 'Χ');
			AddEntityMapping("Delta", 'Δ');
			AddEntityMapping("Epsilon", 'Ε');
			AddEntityMapping("Eta", 'Η');
			AddEntityMapping("Gamma", 'Γ');
			AddEntityMapping("Iota", 'Ι');
			AddEntityMapping("Kappa", 'Κ');
			AddEntityMapping("Lambda", 'Λ');
			AddEntityMapping("Mu", 'Μ');
			AddEntityMapping("Nu", 'Ν');
			AddEntityMapping("Omega", 'Ω');
			AddEntityMapping("Omicron", 'Ο');
			AddEntityMapping("Phi", 'Φ');
			AddEntityMapping("Pi", 'Π');
			AddEntityMapping("Prime", '″');
			AddEntityMapping("Psi", 'Ψ');
			AddEntityMapping("Rho", 'Ρ');
			AddEntityMapping("Sigma", 'Σ');
			AddEntityMapping("Tau", 'Τ');
			AddEntityMapping("Theta", 'Θ');
			AddEntityMapping("Upsilon", 'Υ');
			AddEntityMapping("Xi", 'Ξ');
			AddEntityMapping("Zeta", 'Ζ');
			AddEntityMapping("alefsym", 'ℵ');
			AddEntityMapping("alpha", 'α');
			AddEntityMapping("and", '∧');
			AddEntityMapping("ang", '∠');
			AddEntityMapping("asymp", '≈');
			AddEntityMapping("beta", 'β');
			AddEntityMapping("bull", '•');
			AddEntityMapping("cap", '∩');
			AddEntityMapping("chi", 'χ');
			AddEntityMapping("clubs", '♣');
			AddEntityMapping("cong", '≅');
			AddEntityMapping("crarr", '↵');
			AddEntityMapping("cup", '∪');
			AddEntityMapping("dArr", '⇓');
			AddEntityMapping("darr", '↓');
			AddEntityMapping("delta", 'δ');
			AddEntityMapping("diams", '♦');
			AddEntityMapping("empty", '∅');
			AddEntityMapping("epsilon", 'ε');
			AddEntityMapping("equiv", '≡');
			AddEntityMapping("eta", 'η');
			AddEntityMapping("exist", '∃');
			AddEntityMapping("fnof", 'ƒ');
			AddEntityMapping("forall", '∀');
			AddEntityMapping("frasl", '⁄');
			AddEntityMapping("gamma", 'γ');
			AddEntityMapping("ge", '≥');
			AddEntityMapping("hArr", '⇔');
			AddEntityMapping("harr", '↔');
			AddEntityMapping("hearts", '♥');
			AddEntityMapping("hellip", '…');
			AddEntityMapping("image", 'ℑ');
			AddEntityMapping("infin", '∞');
			AddEntityMapping("int", '∫');
			AddEntityMapping("iota", 'ι');
			AddEntityMapping("isin", '∈');
			AddEntityMapping("kappa", 'κ');
			AddEntityMapping("lArr", '⇐');
			AddEntityMapping("lambda", 'λ');
			AddEntityMapping("lang", '〈');
			AddEntityMapping("larr", '←');
			AddEntityMapping("lceil", '⌈');
			AddEntityMapping("le", '≤');
			AddEntityMapping("lfloor", '⌊');
			AddEntityMapping("lowast", '∗');
			AddEntityMapping("loz", '◊');
			AddEntityMapping("minus", '−');
			AddEntityMapping("mu", 'μ');
			AddEntityMapping("nabla", '∇');
			AddEntityMapping("ne", '≠');
			AddEntityMapping("ni", '∋');
			AddEntityMapping("notin", '∉');
			AddEntityMapping("nsub", '⊄');
			AddEntityMapping("nu", 'ν');
			AddEntityMapping("oline", '‾');
			AddEntityMapping("omega", 'ω');
			AddEntityMapping("omicron", 'ο');
			AddEntityMapping("oplus", '⊕');
			AddEntityMapping("or", '∨');
			AddEntityMapping("otimes", '⊗');
			AddEntityMapping("part", '∂');
			AddEntityMapping("perp", '⊥');
			AddEntityMapping("phi", 'φ');
			AddEntityMapping("pi", 'π');
			AddEntityMapping("piv", 'ϖ');
			AddEntityMapping("prime", '′');
			AddEntityMapping("prod", '∏');
			AddEntityMapping("prop", '∝');
			AddEntityMapping("psi", 'ψ');
			AddEntityMapping("rArr", '⇒');
			AddEntityMapping("radic", '√');
			AddEntityMapping("rang", '〉');
			AddEntityMapping("rarr", '→');
			AddEntityMapping("rceil", '⌉');
			AddEntityMapping("real", 'ℜ');
			AddEntityMapping("rfloor", '⌋');
			AddEntityMapping("rho", 'ρ');
			AddEntityMapping("sdot", '⋅');
			AddEntityMapping("sigma", 'σ');
			AddEntityMapping("sigmaf", 'ς');
			AddEntityMapping("sim", '∼');
			AddEntityMapping("spades", '♠');
			AddEntityMapping("sub", '⊂');
			AddEntityMapping("sube", '⊆');
			AddEntityMapping("sum", '∑');
			AddEntityMapping("sup", '⊃');
			AddEntityMapping("supe", '⊇');
			AddEntityMapping("tau", 'τ');
			AddEntityMapping("there4", '∴');
			AddEntityMapping("theta", 'θ');
			AddEntityMapping("thetasym", 'ϑ');
			AddEntityMapping("trade", '™');
			AddEntityMapping("uArr", '⇑');
			AddEntityMapping("uarr", '↑');
			AddEntityMapping("upsih", 'ϒ');
			AddEntityMapping("upsilon", 'υ');
			AddEntityMapping("weierp", '℘');
			AddEntityMapping("xi", 'ξ');
			AddEntityMapping("zeta", 'ζ');
		}
	}
}
