using System.Runtime.Serialization;

namespace Sdl.LanguagePlatform.Core.Resources
{
	[DataContract]
	public enum LanguageResourceType
	{
		[EnumMember]
		Undefined,
		[EnumMember]
		Variables,
		[EnumMember]
		Abbreviations,
		[EnumMember]
		OrdinalFollowers,
		[EnumMember]
		SegmentationRules,
		[EnumMember]
		TokenizerSettings,
		[EnumMember]
		StemmingRules,
		[EnumMember]
		Stopwords,
		[EnumMember]
		DatePatterns,
		[EnumMember]
		TimePatterns,
		[EnumMember]
		NumberPatterns,
		[EnumMember]
		MeasurementPatterns,
		[EnumMember]
		CharTrigramVector,
		[EnumMember]
		ShortDateFST,
		[EnumMember]
		LongDateFST,
		[EnumMember]
		ShortTimeFST,
		[EnumMember]
		LongTimeFST,
		[EnumMember]
		CurrencySymbols,
		[EnumMember]
		PhysicalUnits,
		[EnumMember]
		NumberFST,
		[EnumMember]
		MeasurementFST,
		[EnumMember]
		GenericRecognizers,
		[EnumMember]
		ShortDateFSTEx,
		[EnumMember]
		LongDateFSTEx,
		[EnumMember]
		ShortTimeFSTEx,
		[EnumMember]
		LongTimeFSTEx,
		[EnumMember]
		NumberFSTEx,
		[EnumMember]
		MeasurementFSTEx,
		[EnumMember]
		CurrencyFST,
		[EnumMember]
		CurrencyFSTEx
	}
}
